name: health_sync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  camera: ^0.11.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  json_theme: ^6.4.1+5
  fl_chart: ^0.68.0
  file_picker: ^8.0.3
  path: ^1.9.0
  google_generative_ai: ^0.4.0
  provider: ^6.1.2
  material_symbols_icons: ^4.2744.0
  device_info_plus: ^10.1.0
  flutter_speed_dial: ^7.0.0
  timeago: ^3.6.1
  animate_z_widget: ^0.0.8
  health: ^10.2.0
  permission_handler: ^11.3.1
  carp_serializable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/theme/theme.json
    - assets/icons/
