// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbPxSxv9XqBiwRp2n6S_Y25ipO3j1XXAw',
    appId: '1:423922817981:web:5daa1b9e3179957d2ad0d4',
    messagingSenderId: '423922817981',
    projectId: 'health-sync-ai',
    authDomain: 'health-sync-ai.firebaseapp.com',
    storageBucket: 'health-sync-ai.appspot.com',
    measurementId: 'G-CHDCNS9F4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTQjqLnXAbUM5aWYr_MeZF_18hTEzzkVs',
    appId: '1:423922817981:android:041bd1ffda2ff7ee2ad0d4',
    messagingSenderId: '423922817981',
    projectId: 'health-sync-ai',
    storageBucket: 'health-sync-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaOtOy4aVhouAOIDxq-Y83W-8j11SRLko',
    appId: '1:423922817981:ios:5f5043cb65d00aa12ad0d4',
    messagingSenderId: '423922817981',
    projectId: 'health-sync-ai',
    storageBucket: 'health-sync-ai.appspot.com',
    iosBundleId: 'com.example.healthSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaOtOy4aVhouAOIDxq-Y83W-8j11SRLko',
    appId: '1:423922817981:ios:ed023766bec5e7ee2ad0d4',
    messagingSenderId: '423922817981',
    projectId: 'health-sync-ai',
    storageBucket: 'health-sync-ai.appspot.com',
    iosBundleId: 'com.example.healthSync.RunnerTests',
  );
}
